

DROP TABLE IF EXISTS customers CASCADE;


DROP TABLE IF EXISTS employees CASCADE;


DROP TABLE IF EXISTS offices CASCADE;

DROP TABLE IF EXISTS orderdetails CASCADE;


DROP TABLE IF EXISTS orders CASCADE;


DROP TABLE IF EXISTS payments CASCADE;


DROP TABLE IF EXISTS productlines CASCADE;

DROP TABLE IF EXISTS products CASCADE;
